General improvements, code quality, version bumps, license header
SpruceLoader/Trunk pull request #4
Opened 2023-04-27 23:43 UTC by xtrm-en

2023-05-11 10:54 UTC, TheKodeToad requested changes
Oh, also throwing exceptions like that doesn't look safe :P

2023-05-11 10:54 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/utils/MappingConfiguration.java
> +    private static MappingConfiguration INSTANCE;
This should be lowercase

2023-05-11 15:01 UTC, xtrm-en commented
> Oh, also throwing exceptions like that doesn't look safe :P

I'd argue it's better to throw the exception if the provided classpath contains an invalid entry.

2023-05-11 15:07 UTC, TheKodeToad commented
I mean the tricking the compiler thing

2023-05-11 17:00 UTC, qtdyn commented
> I mean the tricking the compiler thing

it works :^)

2023-05-25 12:31 UTC, TheKodeToad requested changes
Just a "few" things...

2023-05-25 12:31 UTC, TheKodeToad commented on gradle.properties
> +org.gradle.parallel.threads=4
Is this needed? i'm pretty sure the daemon is default

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/Trunk.java
> +                                0, transformerClassName.lastIndexOf('.')
I don't think needs its own line

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/Trunk.java
> +        for (String entry : classPathEntries) {
The variable seems redundant.

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/Trunk.java
> +                mainClass = fromProperty.get();
It seems weird to compute the value which takes precendence *after* the other values!

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/utils/FunctionalExceptionHandlers.java
> +        return (t) -> {
No parentheses are needed here

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/utils/MappingConfiguration.java
>      private void initialize() {
If you inlined this it would make more sense as the fields could be final!

2023-05-25 12:31 UTC, TheKodeToad commented on src/main/java/xyz/spruceloader/trunk/api/TransformerManager.java
> +            Arrays.stream(prop.split("/")).forEach(
`for (String name : prop.split("/"))` seems like a more natural way to do this... still an improvement

2023-11-11 16:35 UTC, closed without merging